name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # Enable manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '22'

      - name: Install dependencies & configure AWS Cognito Env Vars and Secrets
        run: npm install
        env: 
          ENV: ${{ vars.ENV }}
          REGION: ${{ vars.REGION }}
          USER_POOL_ID: ${{ secrets.USER_POOL_ID }}
          USER_POOL_WEB_CLIENT_ID: ${{ secrets.USER_POOL_WEB_CLIENT_ID }}
          OAUTH_DOMAIN: ${{ secrets.OAUTH_DOMAIN }}
          OAUTH_REDIRECT_SIGN_OUT: ${{ vars.OAUTH_REDIRECT_SIGN_OUT }} 
          OAUTH_REDIRECT_SIGN_RESPONSE_TYPE: ${{ vars.OAUTH_REDIRECT_SIGN_RESPONSE_TYPE }}
          AUTHORITY: ${{ secrets.AUTHORITY }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          REDIRECT_URI: ${{ vars.REDIRECT_URI }}
          SCOPE: ${{ vars.SCOPE }}
          MIGRATION_API_KEY: ${{ secrets.MIGRATION_API_KEY }}

      - name: Fetch Latest Documentation
        run: npm run import

      - name: Build Docusaurus site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
